generic:
  data_path: /home/sumire/discourse_context_mt/data/BSD-master/test.json
  #src_lang: en
  tgt_lang: ja
  #src_context: 0
  #tgt_context: 0
  #dropout: 0.0
  #speaker: False
  #random_context: False
  #tag: False
  #output_dir: "./results/" # Modify here
  batch_size: 8
  model_checkpoint : facebook/xglm-7.5B
  k : 12
  prompt_talk_id : 1548
  max_new_tokens : 128 
  max_length : 512 # 512
  cfg_name : 1-1
