generic:
  data_path: /mnt/data-poseidon/sumire/repos/ContraPro/context_9
  #src_lang: en
  #tgt_lang: de
  src_context: 9
  #tgt_context: 0
  #dropout: 0.0
  #speaker: False
  #random_context: False
  #tag: False
  #output_dir: "./results/" # Modify here
  batch_size: 1
  model_checkpoint : /mnt/data-poseidon/sumire/repos/transformersum/ckpt/distilroberta/epoch=3.ckpt
  #k : 0
  #prompt_type: 1
  #max_new_tokens : 1024 #64 #128 
  #max_length : 1024 #1024 #512 # 512 # 272 should be okay for k = 3# 313 should be ok for k=4
  api: True
  #device: 6
  num_summary_sentences: 3
  cfg_name : transforemersum-distilroberta-ctpro-10-1to4-1
